ModKey: "LMenu"
ResizePercentage: 2

Gaps:
  InnerGap: 10
  OuterGap: 20

Bar:
  Height: 50

Workspaces:
  - Name: 1
    BindToMonitor: "MonitorName"
    CustomDisplayName: "Aa"
    KeepAlive: true
  - Name: 2
  - Name: 3
  - Name: 4
  - Name: 5
  - Name: 6
  - Name: 7
  - Name: 8
  - Name: 9

Keybindings:
  - Command: "focus left"
    Bindings: ["$mod+h"]

  - Command: "focus right"
    Bindings: ["$mod+l"]

  - Command: "focus up"
    Bindings: ["$mod+k"]

  - Command: "focus down"
    Bindings: ["$mod+j"]

  - Command: "move left"
    Bindings: ["$mod+shift+h"]

  - Command: "move right"
    Bindings: ["$mod+shift+l"]

  - Command: "move up"
    Bindings: ["$mod+shift+k"]

  - Command: "move down"
    Bindings: ["$mod+shift+j"]

  - Command: "resize left"
    Bindings: ["$mod+u"]

  - Command: "resize right"
    Bindings: ["$mod+p"]

  - Command: "resize up"
    Bindings: ["$mod+o"]

  - Command: "resize down"
    Bindings: ["$mod+i"]

  - Command: "layout horizontal"
    Bindings: ["$mod+shift+v"]

  - Command: "layout vertical"
    Bindings: ["$mod+v"]

  - Command: "close"
    Bindings: ["$mod+shift+q"]

  - Command: "focus workspace 1"
    Bindings: ["$mod+1"]

  - Command: "focus workspace 2"
    Bindings: ["$mod+2"]

  - Command: "focus workspace 3"
    Bindings: ["$mod+3"]

  - Command: "focus workspace 4"
    Bindings: ["$mod+4"]

  - Command: "focus workspace 5"
    Bindings: ["$mod+5"]

  - Command: "focus workspace 6"
    Bindings: ["$mod+6"]

  - Command: "focus workspace 7"
    Bindings: ["$mod+7"]

  - Command: "focus workspace 8"
    Bindings: ["$mod+8"]

  - Command: "focus workspace 9"
    Bindings: ["$mod+9"]

  - Command: "move to workspace 1"
    Bindings: ["$mod+shift+1"]

  - Command: "move to workspace 2"
    Bindings: ["$mod+shift+2"]

  - Command: "move to workspace 3"
    Bindings: ["$mod+shift+3"]

  - Command: "move to workspace 4"
    Bindings: ["$mod+shift+4"]

  - Command: "move to workspace 5"
    Bindings: ["$mod+shift+5"]

  - Command: "move to workspace 6"
    Bindings: ["$mod+shift+6"]

  - Command: "move to workspace 7"
    Bindings: ["$mod+shift+7"]

  - Command: "move to workspace 8"
    Bindings: ["$mod+shift+8"]

  - Command: "move to workspace 9"
    Bindings: ["$mod+shift+9"]
