gaps:
  inner_gap: 10
  outer_gap: 20

bar:
  height: 25
  components_left:
    - type: "workspaces"
  components_right:
    - type: "clock"

workspaces:
  - name: 1
    bind_to_monitor: "monitorname"
    custom_display_name: "aa"
    keep_alive: true
  - name: 2
  - name: 3
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
  - name: 9

keybindings:
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]

  - command: "focus right"
    bindings: ["Alt+L", "Alt+Right"]

  - command: "focus up"
    bindings: ["Alt+K", "Alt+Up"]

  - command: "focus down"
    bindings: ["Alt+J", "Alt+Down"]

  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]

  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]

  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]

  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  - command: "resize width -2%"
    binding: "Alt+U"

  - command: "resize width +2%"
    binding: "Alt+P"

  - command: "resize height +2%"
    binding: "Alt+O"

  - command: "resize height -2%"
    binding: "Alt+I"

  - command: "layout horizontal"
    binding: "Alt+Shift+V"

  - command: "layout vertical"
    binding: "Alt+V"

  - command: "toggle focus mode"
    binding: "Alt+Space"

  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  - command: "close"
    binding: "Alt+Shift+Q"

  - command: "focus workspace 1"
    binding: "Alt+1"

  - command: "focus workspace 2"
    binding: "Alt+2"

  - command: "focus workspace 3"
    binding: "Alt+3"

  - command: "focus workspace 4"
    binding: "Alt+4"

  - command: "focus workspace 5"
    binding: "Alt+5"

  - command: "focus workspace 6"
    binding: "Alt+6"

  - command: "focus workspace 7"
    binding: "Alt+7"

  - command: "focus workspace 8"
    binding: "Alt+8"

  - command: "focus workspace 9"
    binding: "Alt+9"

  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"

  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"

  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"

  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"

  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"

  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"

  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"

  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"

  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
