ModKey: "Alt"
ResizePercentage: 2

Gaps:
  InnerGap: 10
  OuterGap: 20

Bar:
  Height: 25
  ComponentsLeft:
    - Type: "workspaces"
  ComponentsRight:
    - Type: "clock"

Workspaces:
  - Name: 1
    BindToMonitor: "MonitorName"
    CustomDisplayName: "Aa"
    KeepAlive: true
  - Name: 2
  - Name: 3
  - Name: 4
  - Name: 5
  - Name: 6
  - Name: 7
  - Name: 8
  - Name: 9

Keybindings:
  - Command: "focus left"
    Bindings: ["$mod+H", "$mod+Left"]

  - Command: "focus right"
    Bindings: ["$mod+L", "$mod+Right"]

  - Command: "focus up"
    Bindings: ["$mod+K", "$mod+Up"]

  - Command: "focus down"
    Bindings: ["$mod+J", "$mod+Down"]

  - Command: "move left"
    Bindings: ["$mod+Shift+H", "$mod+Shift+Left"]

  - Command: "move right"
    Bindings: ["$mod+Shift+L", "$mod+Shift+Right"]

  - Command: "move up"
    Bindings: ["$mod+Shift+K", "$mod+Shift+Up"]

  - Command: "move down"
    Bindings: ["$mod+Shift+J", "$mod+Shift+Down"]

  - Command: "resize shrink width"
    Binding: "$mod+U"

  - Command: "resize grow width"
    Binding: "$mod+P"

  - Command: "resize grow height"
    Binding: "$mod+O"

  - Command: "resize shrink height"
    Binding: "$mod+I"

  - Command: "layout horizontal"
    Binding: "$mod+Shift+V"

  - Command: "layout vertical"
    Binding: "$mod+V"

  - Command: "toggle floating"
    Binding: "$mod+Shift+Space"

  - Command: "close"
    Binding: "$mod+Shift+Q"

  - Command: "focus workspace 1"
    Binding: "$mod+1"

  - Command: "focus workspace 2"
    Binding: "$mod+2"

  - Command: "focus workspace 3"
    Binding: "$mod+3"

  - Command: "focus workspace 4"
    Binding: "$mod+4"

  - Command: "focus workspace 5"
    Binding: "$mod+5"

  - Command: "focus workspace 6"
    Binding: "$mod+6"

  - Command: "focus workspace 7"
    Binding: "$mod+7"

  - Command: "focus workspace 8"
    Binding: "$mod+8"

  - Command: "focus workspace 9"
    Binding: "$mod+9"

  - Commands: ["move to workspace 1", "focus workspace 1"]
    Binding: "$mod+Shift+1"

  - Commands: ["move to workspace 2", "focus workspace 2"]
    Binding: "$mod+Shift+2"

  - Commands: ["move to workspace 3", "focus workspace 3"]
    Binding: "$mod+Shift+3"

  - Commands: ["move to workspace 4", "focus workspace 4"]
    Binding: "$mod+Shift+4"

  - Commands: ["move to workspace 5", "focus workspace 5"]
    Binding: "$mod+Shift+5"

  - Commands: ["move to workspace 6", "focus workspace 6"]
    Binding: "$mod+Shift+6"

  - Commands: ["move to workspace 7", "focus workspace 7"]
    Binding: "$mod+Shift+7"

  - Commands: ["move to workspace 8", "focus workspace 8"]
    Binding: "$mod+Shift+8"

  - Commands: ["move to workspace 9", "focus workspace 9"]
    Bindings: ["$mod+Shift+9"]
